---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_ssh: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - lima
  - ddev
  - doxygen
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nss
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search

homebrew_taps:
  - ddev/ddev
  - ngrok/ngrok

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - sequel-ace
  - macvim
  - ngrok
  - slack
  - sublime-text
  - transmit

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

configure_vim: true
vim_base_path: ~/.vim
vim_package_path: pack/vendor
vim_packages:
  - name: fugitive
    url: https://github.com/tpope/vim-fugitive.git
    type: start
  - name: vim-colors-solarized
    url: https://github.com/altercation/vim-colors-solarized.git
    type: opt
  - name: nerdtree
    url: https://github.com/preservim/nerdtree.git
    type: start
  - name: vdebug
    url: https://github.com/vim-vdebug/vdebug.git
    type: start

configure_vscode: true
vscode_extensions:
  # - andrewdavidblum.drupal-smart-snippets
  # - bmewburn.vscode-intelephense-client
  # - clemenspeters.format-json
  # - dmitrydorofeev.empty-indent
  # - ikappas.composer
  # - juniormucciolo.drupal-7-snippets
  # - marcostazi.vs-code-drupal
  # - mblode.twig-language-2
  # - ms-azuretools.vscode-docker
  # - ms-python.isort
  # - ms-python.python
  # - ms-python.vscode-pylance
  # - ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64 # FIXME
  # - ms-toolsai.jupyter-keymap
  # - ms-toolsai.jupyter-renderers
  # - ms-toolsai.vscode-jupyter-cell-tags
  # - ms-toolsai.vscode-jupyter-slideshow
  # - ms-vscode-remote.remote-containers
  # - neilbrayfield.php-docblocker
  # - pauloamgomes.drupal7-hooks-snippets
  # - ritwickdey.liveserver
  # - tsega.drupal-8-javascript-snippets
  # - tsega.drupal-8-twig-snippets
  # - valeryanm.vscode-phpsab
  - xdebug.php-debug

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
